apiVersion: kubernetes.vault.upbound.io/v1alpha1
kind: AuthBackendRole
metadata:
  name: webapp-role
spec:
  forProvider:
    backend: "kubernetes"
    roleName: "webapp-role"
    boundServiceAccountNames: ["webapp-sa"]
    boundServiceAccountNamespaces: ["default"]
    tokenPolicies: ["webapp-reader"]