releases:
  - name: tempo
    namespace: monitoring
    chart: ./monitoring/tempo

  - name: pyroscope
    namespace: monitoring
    chart: ./monitoring/pyroscope

  - name: prometheus
    namespace: monitoring
    chart: ./monitoring/prometheus

  - name: loki
    namespace: monitoring
    chart: ./monitoring/loki
    needs: [ monitoring/prometheus ]

  - name: alloy
    namespace: monitoring
    chart: ./monitoring/alloy
    needs: [ monitoring/loki, monitoring/tempo, monitoring/pyroscope ]

  - name: vault
    namespace: secrets
    chart: ./secrets/vault