releases:
  - name: cert-manager
    namespace: cert
    chart: ./cert/cert-manager

  - name: tempo
    namespace: monitoring
    chart: ./monitoring/tempo

  - name: pyroscope
    namespace: monitoring
    chart: ./monitoring/pyroscope

  - name: prometheus
    namespace: monitoring
    chart: ./monitoring/prometheus

  - name: loki
    namespace: monitoring
    chart: ./monitoring/loki
    needs:
      - prometheus

  - name: alloy
    namespace: monitoring
    chart: ./monitoring/alloy
    needs:
      - loki
      - tempo
      - pyroscope

  - name: vault
    namespace: secrets
    chart: ./secrets/vault