apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.grpcPort }}
            - containerPort: {{ .Values.service.diagPort }}
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.global.otelEndpoint | quote }}
            - name: DB_HOST
              # Для users это будет 'my-platform-postgresql'
              value: {{ .Values.db.host | quote }}
          {{- if .Values.secrets.enabled }}
          volumeMounts:
            - name: secrets-vol
              mountPath: /etc/secrets
              readOnly: true
          {{- end }}
      {{- if .Values.secrets.enabled }}
      volumes:
        - name: secrets-vol
          secret:
            secretName: {{ .Values.secrets.name }}
      {{- end }}