docker_build(
  'tilt.dev/sso',
  '.',
  live_update=[
    sync('.', '/app'),
    run('cd /app && go build -o /app/app cmd/app/*.go', trigger='./cmd/app/'),
    run('kill -HUP 1', trigger='./cmd/app/'),
  ]
)

k8s_yaml([
  'k8s/sso-deployment.yaml',
  'k8s/sso-service.yaml',
])

k8s_resource(
  'sso',
  resource_deps=['mongodb', 'otel-collector'],
  port_forwards=['9011:9011', '9012:9012'],
  labels=['app', 'sso']
)