alertmanager:
  enabled: false

nodeExporter:
  enabled: true

prometheus-node-exporter:
  enabled: true

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    enableFeatures:
      - exemplar-storage
      - native-histograms

grafana:
  adminPassword: "admin"
  service:
    type: NodePort

  plugins:
    - grafana-exploretraces-app

  additionalDataSources:
    - name: Tempo
      type: tempo
      url: http://tempo.telemetry.svc.cluster.local:3200
      access: proxy
    - name: Loki
      type: loki
      url: http://loki-gateway.telemetry.svc.cluster.local:80
      access: proxy
      jsonData:
        httpHeaderName1: "X-Scope-OrgID"
