kube-prometheus-stack:
  alertmanager:
    enabled: false

  nodeExporter:
    enabled: true

  prometheus-node-exporter:
    enabled: true

  prometheus:
    prometheusSpec:
      enableRemoteWriteReceiver: true
      enableFeatures:
        - exemplar-storage
        - native-histograms

  grafana:
    adminPassword: "admin"
    service:
      type: NodePort

    plugins:
      - grafana-exploretraces-app

    additionalDataSources:
      - name: Tempo
        type: tempo
        url: http://observability-tempo.monitoring.svc.cluster.local:3100
        access: proxy
      - name: Loki
        type: loki
        url: http://loki:3100
        access: proxy