apiVersion: v2
name: my-platform
description: My Microservices Stack
version: 0.1.0
type: application

dependencies:
  - name: postgresql
    version: 15.5.x
    repository: https://charts.bitnami.com/bitnami
  - name: mongodb
    version: 15.6.x
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 19.x.x
    repository: https://charts.bitnami.com/bitnami