global:
  otelEndpoint: "otel-lgtm-collector:4317"

otel-lgtm:
  enabled: true
  grafana:
    service:
      type: LoadBalancer

postgresql:
  auth:
    database: users_db
    username: misha
  primary:
    persistence:
      size: 8Gi

mongodb:
  auth:
    rootPassword: "securepassword"