apiVersion: kv.vault.upbound.io/v1alpha1
kind: SecretV2
metadata:
  name: microservice-vault-secret
spec:
  forProvider:
    mount: "secret"
    name: "microservice/ssh-keys"
    dataJsonSecretRef:
      name: temp-rsa-key-data
      namespace: crossplane-system
      key: attribute.private_key_pem