apiVersion: auth.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: webapp-policy
spec:
  forProvider:
    name: "webapp-reader"
    policy: |
      path "secret/data/webapp/*" {
        capabilities = ["read", "list"]
      }