vault:
  global:
    enabled: true

  injector:
    enabled: true
    replicas: 1

  server:
    dev:
      enabled: true
#    postStart:
#      - /bin/sh
#      - -c
#      - /vault/userconfig/myscript/run.sh