alloy:
  configMap:
    content: |
      otelcol.receiver.otlp "otlp_receiver" {
        grpc {
          endpoint = "0.0.0.0:4317"
        }
        http {
          endpoint = "0.0.0.0:4318"
        }
        output {
          traces = [otelcol.exporter.otlp.tempo.input]
          logs   = [otelcol.exporter.loki.loki_exporter.input]
          metrics = [otelcol.processor.batch.default.input]
        }
      }
      
      otelcol.processor.batch "default" {
        output {
          metrics = [otelcol.exporter.prometheus.to_prometheus.input]
        }
      }

      otelcol.exporter.prometheus "to_prometheus" {
        forward_to = [prometheus.remote_write.local_prom.receiver]
      }

      prometheus.remote_write "local_prom" {
        endpoint {
          url = "http://prometheus-stack-kube-prom-prometheus.telemetry.svc.cluster.local:9090/api/v1/write"
        }
      }
      
      otelcol.exporter.otlp "tempo" {
        client {
          endpoint = "tempo.telemetry.svc.cluster.local:4317"
          tls {
            insecure = true
          }
        }
      }
      
      otelcol.exporter.loki "loki_exporter" {
        forward_to = [loki.write.local_loki.receiver]
      }

      loki.write "local_loki" {
        endpoint {
          url = "http://loki-gateway.telemetry.svc.cluster.local:80/loki/api/v1/push"
        }
      }

  extraPorts:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP