apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: transit
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "13"
spec:
  connection:
    address: {{ .Values.vault.url }}
  authentication:
    path: kubernetes
    role: policy-admin
  path: transit
  type: transit