apiVersion: redhatcop.redhat.io/v1alpha1
kind: SecretEngineMount
metadata:
  name: transit
  namespace: {{ .Release.Namespace }}
spec:
  connection:
    address: {{ .Values.vault.url }}
  authentication:
    path: kubernetes
    role: policy-admin
  path: transit
  type: transit