apiVersion: redhatcop.redhat.io/v1alpha1
kind: Policy
metadata:
  name: policy
  namespace: {{ .Release.Namespace }}
spec:
  connection:
    address: {{ .Values.vault.url }}
  authentication:
    path: kubernetes
    role: vault-admin
  policy: |
    path "secret/data/sso-service/*" {
      capabilities = ["read"]
    }