apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: role
  namespace: {{ .Release.Namespace }}
spec:
  connection:
    address: {{ .Values.vault.url }}
  authentication:
    path: kubernetes
    role: policy-admin
  path: kubernetes
  targetServiceAccounts:
    - sso-service-sa
  targetNamespaces:
    targetNamespaceSelector:
      matchLabels:
        team: "team"
  policies:
    - sso-policy