apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "vault.fullname" . }}-configurator
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: {{ include "vault.fullname" . }}
      containers:
        - name: terraform
          image: hashicorp/terraform:1.7.0
          workingDir: /conf
          command: ["/bin/sh", "-c"]
          args:
            - |
              terraform init \
              -backend-config="secret_suffix=vault-state" \
              -backend-config="namespace={{ .Release.Namespace }}" \
              -backend-config="in_cluster_config=true" && \
              
              terraform apply -auto-approve
          env:
            - name: VAULT_ADDR
              value: "http://{{ include "vault.fullname" . }}:8200"
          volumeMounts:
            - name: tf-config
              mountPath: /conf
      volumes:
        - name: tf-config
          configMap:
            name: {{ include "vault.fullname" . }}-tf-files
      restartPolicy: Never
  backoffLimit: 1