apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secrets

resources:
  - ../../base

helmCharts:
  - name: secrets-store-csi-driver
    releaseName: secrets-store-csi-driver
    namespace: secrets
    repo: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    version: 1.6.0
    valuesFile: values.yaml