# values.yaml
replicaCount: 2

image:
  repository: ghcr.io/your-user/users-app
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

service:
  type: ClusterIP
  port: 50051

env:
  - name: DB_DATABASE
    value: "users_db"
  - name: REDIS_PORT
    value: "6379"