# Deployment mode: SingleBinary (simple), SimpleScalable (medium), Distributed (large)
deploymentMode: SingleBinary

# Number of replicas
singleBinary:
  replicas: 1

# Component replicas
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0

# Caching
chunksCache:
  enabled: false
resultsCache:
  enabled: false

# Helm test
test:
  enabled: false

# All loki settings combined under one key
loki:
  auth_enabled: false

  server:
    http_listen_port: 3100

  storage:
    type: 'filesystem'

  common:
    ring:
      instance_addr: 127.0.0.1
      kvstore:
        store: inmemory
    replication_factor: 1
    path_prefix: /tmp/loki

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem
        schema: v13

  storage_config:
    filesystem:
      directory: /tmp/loki/chunks